### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by TetianaSeniv** [TetianaSeniv/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by vtenq** [comment]
“Get going. Move forward. Aim High. Plan a takeoff. Don’t just sit on the runway and hope someone will come along and push the airplane. It simply won’t happen. Change your attitude and gain some altitude. Believe me, you’ll love it up here.”

**Comment by TetianaSeniv** [comment]
Дякую
