### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by TetianaSeniv** [TetianaSeniv/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by vtenq** [comment]
<div>
                    <h1 class="name">Donald Trump</h1>
                    <ul class="contacts">
                      <li>
                        <a href="mailto:donald.trump@gmail.com">donald.trump@gmail.com</a>
                      </li>
                      <li>
                        <a href="http://en.wikipedia.org/wiki/Donald_Trump" target="_blank"
                          rel="noopener noreferrer">Wikipedia</a>
                      </li>
                      <li>
                        <a href="http://twitter.com/realdonaldtrump" target="_blank"
                          rel="noopener noreferrer">Twitter</a>
                      </li>
                    </ul>
                  </div>
