### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by TetianaSeniv** [TetianaSeniv/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by vtenq** [comment]
</div>
          <div class="row">
            <div class="sixteen wide column">
              <div class="fat divider"></div>
            </div>
          </div>
          <div class="row">
            <div class="ten wide column">

              <h3>Experience</h3>
              <ul class="timeline">
                <li>
                  <p><small>2017</small></p>
                  <p>Trump and his businesses had been involved in more than 4,000 state and federal legal actions,
                    according to a running tally by USA Today</p>
                </li>
                <li>
                  <p><small>2016</small></p>
                  <p>In 2016, the New York State Attorney General's office notified the Trump Foundation that the
                    foundation appeared to be in violation of New York laws regarding charities, ordering it to
                    immediately cease its fundraising activities in New York.</p>
                </li>
                <li>
                  <p><small>2015</small></p>
                  <p>In February 2015, Trump stated that he was "not ready" to sign on for another season of the show
                    because of the possibility of a presidential run.</p>
                </li>
                <li>
                  <p><small>2014</small></p>
                  <p>A February 2014 Quinnipiac poll had shown Trump losing to the more popular Cuomo by 37 points in a
                    hypothetical election.</p>
                </li>
              </ul>
              
              <h3>Business career</h3>
              <ul class="timeline">
                <li>
                  <p><small>Real estate</small></p>
                  <p>In 1968, Trump began his career at his father Fred's real estate development company, E. Trump &
                    Son, which, among other interests, owned middle-class rental housing in New York City's outer
                    boroughs. Trump worked for his father to revitalize the Swifton Village apartment complex in
                    Cincinnati, Ohio, which the elder Trump had bought in 1964. The management of the property was sued
                    for racial discrimination in 1969; the suit "was quietly settled at Fred Trump's direction." The
                    Trumps sold the property in 1972, with vacancy on the rise.</p>
                </li>
                <li>
                  <p><small>Manhattan developments</small></p>
                  <p>In 1978, Trump launched his Manhattan real estate business by purchasing a 50 percent stake in the
                    derelict Commodore Hotel, located next to Grand Central Terminal. The purchase was funded largely by
                    a $70 million construction loan that was guaranteed jointly by Fred Trump and the Hyatt hotel chain.
                    When the remodeling was finished, the hotel reopened in 1980 as the Grand Hyatt Hotel.</p>
                </li>
                <li>
                  <p><small>Palm Beach estate</small></p>
                  <p>In 1985, Trump acquired the Mar-a-Lago estate in Palm Beach, Florida, for $10 million, $7 million
                    for the real estate and $3 million for the furnishings. His initial offer of $28 million had been
                    rejected, and he was able to obtain the property for the lower price after a real-estate market
                    "slump". The home was built in the 1920s by heiress and socialite Marjorie Merriweather Post.</p>
                </li>
                <li>
                  <p><small>Atlantic City casinos</small></p>
                  <p>After New Jersey legalized casino gambling in 1977, Trump traveled to Atlantic City to explore new
                    business opportunities. Seven years later, he opened Harrah's at Trump Plaza hotel and casino; the
                    project was built by Trump with financing from the Holiday Corporation, who also managed its
                    operation. It was renamed "Trump Plaza" soon after it opened.</p>
                </li>
              </ul>
            </div>
