### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by TetianaSeniv** [TetianaSeniv/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vtenq** [comment]
<div class="six wide column">
              
              <section>
                <h3>Religion</h3>
                <p class="tags small">Presbyterian</p>
              </section>
              
              <section>
                <h3>Health</h3>
                <p class="tags small">Trump does not drink alcohol, a reaction to his older brother Fred Trump Jr.'s
                  alcoholism and early death.He has stated that he has never smoked cigarettes or used drugs, including
                  marijuana.In December 2015, Trump's personal physician, Harold Bornstein, released a superlative-laden
                  letter of health, which stated that Trump's "physical strength and stamina are extraordinary.</p>
              </section>
              
              <section>
                <h3>Wealth</h3>
                <p class="tags small">In 1982, Trump was listed on the initial Forbes List of wealthy individuals as
                  having a share of his family's estimated $200 million net worth. His financial losses in the 1980s
                  caused him to be dropped from the list between 1990 and 1995, and reportedly obliged him to borrow
                  from his siblings' trusts in 1993.In its 2019 billionaires ranking, Forbes estimated Trump's net worth
                  at $3.1 billion (715th in the world, 259th in the U.S.) making him one of the richest politicians in
                  American history and the first billionaire American president. During the three years since Trump
                  announced his presidential run in 2015, Forbes estimated his net worth declined 31% and his ranking
                  fell 138 spots.</p>
              </section>
